### ISSUE TITLE
How to turn on beacon discovery ?

### ISSUE THREAD

**Issue by dhruvagarwal** [mrquincle/bluenet#11]
Hey , i tried creating a sample HRM application and have flashed it successfully into nordic nRF51822.
I want the chip to be discovered as a beacon in my android phone on nRF beacon app but it is not discoverable as a beacon but as a simple bluetooth device.
How is the beacon recovery switched on ? Is it via application code .. if so then what library/method/way is used ?

**Comment by mrquincle** [comment]
@dhruvagarwal Thanks for asking. I just added a little section to the `README` file that explains about how to turn on iBeacon functionality. Note that then the normal services do not work.

It is basically just a define in the main file:

    #define IBEACON

The code that is then turned on you can find in https://github.com/mrquincle/bluenet/blob/master/src/BluetoothLE.cpp in the `class IBeacon`.
